#!/usr/bin/env bash
set -euo pipefail

root="$(dirname "$(realpath "$0")")"
mkdir -p "$root/build"

# Fail before the expensive native build if the generated ABI inventory or
# linker exports have drifted from the vendored HiGHS header.
node "$root/scripts/generate-highs-api.mjs" --check

# The extended runtime is authored in TypeScript and emitted as an Emscripten
# post-JS file. Keeping this as a separate compile step makes the handwritten
# marshalling code type-checkable without changing the generated loader.
"$root/node_modules/.bin/tsc" -p "$root/tsconfig.runtime.json"

cd "$root/build"

# Run emconfigure with the normal configure command as an argument.
emcmake cmake ../HiGHS \
	-DZLIB=OFF \
	-DFAST_BUILD=OFF \
	-DBUILD_SHARED_LIBS=OFF \
	-DHIGHSINT64=OFF \
	-DHIGHS_NO_DEFAULT_THREADS=ON

# Run emmake with the normal make to generate wasm object files.
emmake make -j8 libhighs

# Compile the linked code generated by make to JavaScript + WebAssembly.
# 'project.o' should be replaced with the make output for your project, and
# you may need to rename it if it isn't something emcc recognizes
# (for example, it might have a different suffix like 'project.so' or
# 'project.so.1', or no suffix like just 'project' for an executable).
# If the project output is a library, you may need to add your 'main.c' file
# here as well.
# [-Ox] represents build optimisations (discussed in the next section).
emcc -O3 \
	-s EXPORTED_FUNCTIONS="@$root/exported_functions.json" \
	-s EXPORTED_RUNTIME_METHODS="['cwrap','addFunction','removeFunction','UTF8ToString']" \
	-s MODULARIZE=1 \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s ALLOW_TABLE_GROWTH=1 \
	-s STACK_SIZE=4194304 \
	-flto \
	-I "$root/HiGHS/highs" \
	-I "$root/build" \
	--pre-js "$root/src/pre.js" \
	--post-js "$root/src/post.js" \
	--post-js "$root/build/generated/extended.js" \
	"$root/src/highs_js_bridge.cpp" \
	lib/*.a -o highs.js

# Build a native ES module loader that references the same highs.wasm filename.
# Both commands use the same object graph and link flags, so the second link
# replaces highs.wasm with the same single-threaded binary.
emcc -O3 \
	-s EXPORTED_FUNCTIONS="@$root/exported_functions.json" \
	-s EXPORTED_RUNTIME_METHODS="['cwrap','addFunction','removeFunction','UTF8ToString']" \
	-s MODULARIZE=1 \
	-s EXPORT_ES6=1 \
	-s ENVIRONMENT="web,worker,node" \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s ALLOW_TABLE_GROWTH=1 \
	-s STACK_SIZE=4194304 \
	-flto \
	-I "$root/HiGHS/highs" \
	-I "$root/build" \
	--pre-js "$root/src/pre.js" \
	--post-js "$root/src/post.js" \
	--post-js "$root/build/generated/extended.js" \
	"$root/src/highs_js_bridge.cpp" \
	lib/*.a -o highs.mjs
