
var Module = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Module) {
  Module = Module || {};


var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});const k=[],ca=[];f.print=a=>k.push(a);f.printErr=a=>ca.push(a);var m={},r;for(r in f)f.hasOwnProperty(r)&&(m[r]=f[r]);var da="./this.program";function ea(a,b){throw b;}var fa="object"===typeof window,v="function"===typeof importScripts,ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,x="",ia,ja,ka,z,A;
if(ha)x=v?require("path").dirname(x)+"/":__dirname+"/",ia=function(a,b){z||(z=require("fs"));A||(A=require("path"));a=A.normalize(a);return z.readFileSync(a,b?null:"utf8")},ka=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||C("Assertion failed: undefined");return a},ja=function(a,b,c){z||(z=require("fs"));A||(A=require("path"));a=A.normalize(a);z.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",
function(a){if(!(a instanceof la))throw a;}),process.on("unhandledRejection",function(a){throw a;}),ea=function(a,b){if(noExitRuntime||0<ma)throw process.exitCode=a,b;b instanceof la||D("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(fa||v)v?x=self.location.href:"undefined"!==typeof document&&document.currentScript&&(x=document.currentScript.src),_scriptDir&&(x=_scriptDir),0!==x.indexOf("blob:")?x=x.substr(0,x.replace(/[?#].*/,"").lastIndexOf("/")+
1):x="",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=f.print||console.log.bind(console),D=f.printErr||console.warn.bind(console);
for(r in m)m.hasOwnProperty(r)&&(f[r]=m[r]);m=null;f.thisProgram&&(da=f.thisProgram);f.quit&&(ea=f.quit);var E;f.wasmBinary&&(E=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&C("no native wasm support detected");var oa,pa=!1;function qa(a){var b=f["_"+a];b||C("Assertion failed: Cannot call unknown function "+(a+", make sure it is exported"));return b}
function ra(a,b,c,d){var e={string:function(p){var t=0;if(null!==p&&void 0!==p&&0!==p){var y=(p.length<<2)+1;t=sa(y);ta(p,F,t,y)}return t},array:function(p){var t=sa(p.length);G.set(p,t);return t}};a=qa(a);var g=[],l=0;if(d)for(var n=0;n<d.length;n++){var w=e[c[n]];w?(0===l&&(l=ua()),g[n]=w(d[n])):g[n]=d[n]}c=a.apply(null,g);return c=function(p){0!==l&&va(l);return"string"===b?wa(p):"boolean"===b?!!p:p}(c)}var xa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&xa)return xa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function wa(a){return a?H(F,a,void 0):""}
function ta(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ya(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var za,G,F,Aa,I;function Ba(){var a=oa.buffer;za=a;f.HEAP8=G=new Int8Array(a);f.HEAP16=Aa=new Int16Array(a);f.HEAP32=I=new Int32Array(a);f.HEAPU8=F=new Uint8Array(a);f.HEAPU16=new Uint16Array(a);f.HEAPU32=new Uint32Array(a);f.HEAPF32=new Float32Array(a);f.HEAPF64=new Float64Array(a)}var Ca,Da=[],Ea=[],Fa=[],ma=0;
function Ga(){var a=f.preRun.shift();Da.unshift(a)}var J=0,Ha=null,K=null;f.preloadedImages={};f.preloadedAudios={};function C(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";D(a);pa=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ia(){return L.startsWith("data:application/octet-stream;base64,")}var L;L="highs.wasm";if(!Ia()){var Ja=L;L=f.locateFile?f.locateFile(Ja,x):x+Ja}
function Ka(){var a=L;try{if(a==L&&E)return new Uint8Array(E);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){C(b)}}
function La(){if(!E&&(fa||v)){if("function"===typeof fetch&&!L.startsWith("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ka()});if(ja)return new Promise(function(a,b){ja(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ka()})}var M,Ma;
function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Oa;"number"===typeof c?void 0===b.ga?Ca.get(c)():Ca.get(c)(b.ga):c(void 0===b.ga?null:b.ga)}}}function Oa(a){this.Y=a-16;this.Ha=function(b){I[this.Y+4>>2]=b};this.Ea=function(b){I[this.Y+8>>2]=b};this.Fa=function(){I[this.Y>>2]=0};this.Da=function(){G[this.Y+12>>0]=0};this.Ga=function(){G[this.Y+13>>0]=0};this.xa=function(b,c){this.Ha(b);this.Ea(c);this.Fa();this.Da();this.Ga()}}var Pa=0;
function Qa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Ra(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Qa(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Sa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ta(a){if("/"===a)return"/";a=Ra(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ua(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){C("randomDevice")}}
function Va(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Qa(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],X:b};Ya(a,Za)}
var Za={open:function(a){var b=Wa[a.node.rdev];if(!b)throw new O(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.X.flush(a.tty)},flush:function(a){a.tty.X.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.X.pa)throw new O(60);for(var e=0,g=0;g<d;g++){try{var l=a.tty.X.pa(a.tty)}catch(n){throw new O(29);}if(void 0===l&&0===e)throw new O(6);if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.X.ia)throw new O(60);try{for(var e=
0;e<d;e++)a.tty.X.ia(a.tty,b[c+e])}catch(g){throw new O(29);}d&&(a.node.timestamp=Date.now());return e}},ab={pa:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.alloc(256),d=0;try{d=z.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==
b&&(b+="\n"));if(!b)return null;a.input=$a(b,!0)}return a.input.shift()},ia:function(a,b){null===b||10===b?(na(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(H(a.output,0)),a.output=[])}},bb={ia:function(a,b){null===b||10===b?(D(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(D(H(a.output,0)),a.output=[])}},P={R:null,T:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.R||(P.R={dir:{node:{U:P.M.U,S:P.M.S,lookup:P.M.lookup,aa:P.M.aa,rename:P.M.rename,unlink:P.M.unlink,rmdir:P.M.rmdir,readdir:P.M.readdir,symlink:P.M.symlink},stream:{W:P.N.W}},file:{node:{U:P.M.U,S:P.M.S},stream:{W:P.N.W,read:P.N.read,write:P.N.write,ka:P.N.ka,qa:P.N.qa,sa:P.N.sa}},link:{node:{U:P.M.U,S:P.M.S,readlink:P.M.readlink},stream:{}},la:{node:{U:P.M.U,S:P.M.S},stream:cb}});c=db(a,b,c,d);16384===(c.mode&61440)?(c.M=P.R.dir.node,
c.N=P.R.dir.stream,c.L={}):32768===(c.mode&61440)?(c.M=P.R.file.node,c.N=P.R.file.stream,c.O=0,c.L=null):40960===(c.mode&61440)?(c.M=P.R.link.node,c.N=P.R.link.stream):8192===(c.mode&61440)&&(c.M=P.R.la.node,c.N=P.R.la.stream);c.timestamp=Date.now();a&&(a.L[b]=c,a.timestamp=c.timestamp);return c},Pa:function(a){return a.L?a.L.subarray?a.L.subarray(0,a.O):new Uint8Array(a.L):new Uint8Array(0)},ma:function(a,b){var c=a.L?a.L.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,
256)),c=a.L,a.L=new Uint8Array(b),0<a.O&&a.L.set(c.subarray(0,a.O),0))},Ba:function(a,b){if(a.O!=b)if(0==b)a.L=null,a.O=0;else{var c=a.L;a.L=new Uint8Array(b);c&&a.L.set(c.subarray(0,Math.min(b,a.O)));a.O=b}},M:{U:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.O:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);
b.ctime=new Date(a.timestamp);b.va=4096;b.blocks=Math.ceil(b.size/b.va);return b},S:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Ba(a,b.size)},lookup:function(){throw eb[44];},aa:function(a,b,c,d){return P.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=fb(b,c)}catch(g){}if(d)for(var e in d.L)throw new O(55);}delete a.parent.L[a.name];a.parent.timestamp=Date.now();a.name=c;b.L[c]=a;b.timestamp=a.parent.timestamp;
a.parent=b},unlink:function(a,b){delete a.L[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=fb(a,b),d;for(d in c.L)throw new O(55);delete a.L[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.L)a.L.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},N:{read:function(a,b,c,d,e){var g=a.node.L;if(e>=a.node.O)return 0;a=Math.min(a.node.O-
e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===G.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.L||a.L.subarray)){if(g)return a.L=b.subarray(c,c+d),a.O=d;if(0===a.O&&0===e)return a.L=b.slice(c,c+d),a.O=d;if(e+d<=a.O)return a.L.set(b.subarray(c,c+d),e),d}P.ma(a,e+d);if(a.L.subarray&&b.subarray)a.L.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.L[e+g]=b[c+g];a.O=Math.max(a.O,e+
d);return d},W:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.O);if(0>b)throw new O(28);return b},ka:function(a,b,c){P.ma(a.node,b+c);a.node.O=Math.max(a.node.O,b+c)},qa:function(a,b,c,d,e,g){if(0!==b)throw new O(28);if(32768!==(a.node.mode&61440))throw new O(43);a=a.node.L;if(g&2||a.buffer!==za){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;C();c=void 0;if(!c)throw new O(48);G.set(a,c)}else d=!1,c=a.byteOffset;return{Y:c,
Na:d}},sa:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new O(43);if(e&2)return 0;P.N.write(a,b,0,d,c,!1);return 0}}},gb=null,hb={},Q=[],ib=1,R=null,jb=!0,O=null,eb={};
function S(a,b){a=Va("/",a);b=b||{};if(!a)return{path:"",node:null};var c={oa:!0,ja:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ja)throw new O(32);a=Qa(a.split("/").filter(function(l){return!!l}),!1);var e=gb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=fb(e,a[d]);c=Ra(c+"/"+a[d]);e.ba&&(!g||g&&b.oa)&&(e=e.ba.root);if(!g||b.na)for(g=0;40960===(e.mode&61440);)if(e=kb(c),c=Va(Sa(c),e),e=S(c,{ja:b.ja}).node,40<g++)throw new O(32);}return{path:c,node:e}}
function lb(a){for(var b;;){if(a===a.parent)return a=a.T.ra,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function fb(a,b){var c;if(c=(c=nb(a,"x"))?c:a.M.lookup?0:2)throw new O(c,a);for(c=R[mb(a.id,b)];c;c=c.Aa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.M.lookup(a,b)}
function db(a,b,c,d){a=new ob(a,b,c,d);b=mb(a.parent.id,a.name);a.Aa=R[b];return R[b]=a}var pb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function qb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function nb(a,b){if(jb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function rb(a,b){try{return fb(a,b),20}catch(c){}return nb(a,"wx")}
function sb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new O(33);}function tb(a,b){ub||(ub=function(){},ub.prototype={});var c=new ub,d;for(d in a)c[d]=a[d];a=c;b=sb(b);a.fd=b;return Q[b]=a}var cb={open:function(a){a.N=hb[a.node.rdev].N;a.N.open&&a.N.open(a)},W:function(){throw new O(70);}};function Ya(a,b){hb[a]={N:b}}
function vb(a,b){var c="/"===b,d=!b;if(c&&gb)throw new O(10);if(!c&&!d){var e=S(b,{oa:!1});b=e.path;e=e.node;if(e.ba)throw new O(10);if(16384!==(e.mode&61440))throw new O(54);}b={type:a,Qa:{},ra:b,za:[]};a=a.T(b);a.T=b;b.root=a;c?gb=a:e&&(e.ba=b,e.T&&e.T.za.push(b))}function wb(a,b,c){var d=S(a,{parent:!0}).node;a=Ta(a);if(!a||"."===a||".."===a)throw new O(28);var e=rb(d,a);if(e)throw new O(e);if(!d.M.aa)throw new O(63);return d.M.aa(d,a,b,c)}function T(a){return wb(a,16895,0)}
function xb(a,b,c){"undefined"===typeof c&&(c=b,b=438);wb(a,b|8192,c)}function yb(a,b){if(!Va(a))throw new O(44);var c=S(b,{parent:!0}).node;if(!c)throw new O(44);b=Ta(b);var d=rb(c,b);if(d)throw new O(d);if(!c.M.symlink)throw new O(63);c.M.symlink(c,b,a)}function kb(a){a=S(a).node;if(!a)throw new O(44);if(!a.M.readlink)throw new O(28);return Va(lb(a.parent),a.M.readlink(a))}
function U(a,b,c,d){if(""===a)throw new O(44);if("string"===typeof b){var e=pb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Ra(a);try{g=S(a,{na:!(b&131072)}).node}catch(l){}}e=!1;if(b&64)if(g){if(b&128)throw new O(20);}else g=wb(a,c,0),e=!0;if(!g)throw new O(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new O(54);if(!e&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==qb(b)||b&512)?31:nb(g,qb(b)):44))throw new O(c);if(b&512){c=g;c="string"===typeof c?S(c,{na:!0}).node:c;if(!c.M.S)throw new O(63);if(16384===(c.mode&61440))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);if(e=nb(c,"w"))throw new O(e);c.M.S(c,{size:0,timestamp:Date.now()})}b&=-131713;d=tb({node:g,path:lb(g),flags:b,seekable:!0,position:0,N:g.N,Ma:[],error:!1},d);d.N.open&&d.N.open(d);!f.logReadFiles||b&1||(zb||(zb={}),a in zb||(zb[a]=1));return d}
function Ab(a){if(null===a.fd)throw new O(8);a.ha&&(a.ha=null);try{a.N.close&&a.N.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}a.fd=null}function Bb(a,b,c){if(null===a.fd)throw new O(8);if(!a.seekable||!a.N.W)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.N.W(a,b,c);a.Ma=[]}
function Cb(a,b,c,d,e){var g=void 0;if(0>d||0>g)throw new O(28);if(null===a.fd)throw new O(8);if(0===(a.flags&2097155))throw new O(8);if(16384===(a.node.mode&61440))throw new O(31);if(!a.N.write)throw new O(28);a.seekable&&a.flags&1024&&Bb(a,0,2);var l="undefined"!==typeof g;if(!l)g=a.position;else if(!a.seekable)throw new O(70);b=a.N.write(a,b,c,d,g,e);l||(a.position+=b);return b}
function Db(a){var b=b||{};b.flags=b.flags||577;var c=U("m.lp",b.flags,b.mode);if("string"===typeof a){var d=new Uint8Array(ya(a)+1);a=ta(a,d,0,d.length);Cb(c,d,0,a,b.wa)}else if(ArrayBuffer.isView(a))Cb(c,a,0,a.byteLength,b.wa);else throw Error("Unsupported data type");Ab(c)}
function Fb(){O||(O=function(a,b){this.node=b;this.Ca=function(c){this.V=c};this.Ca(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){eb[a]=new O(a);eb[a].stack="<generic error, no stack>"}))}var Gb;function Hb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function V(a,b,c){a=Ra("/dev/"+a);var d=Hb(!!b,!!c);Ib||(Ib=64);var e=Ib++<<8|0;Ya(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,l,n,w){for(var p=0,t=0;t<w;t++){try{var y=b()}catch(N){throw new O(29);}if(void 0===y&&0===p)throw new O(6);if(null===y||void 0===y)break;p++;l[n+t]=y}p&&(g.node.timestamp=Date.now());return p},write:function(g,l,n,w){for(var p=0;p<w;p++)try{c(l[n+p])}catch(t){throw new O(29);}w&&(g.node.timestamp=Date.now());return p}});
xb(a,d,e)}var Ib,W={},ub,zb,X=void 0;function Y(){X+=4;return I[X-4>>2]}function Z(a){a=Q[a];if(!a)throw new O(8);return a}var Jb;Jb=ha?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};var Kb={};
function Lb(){if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Kb)void 0===Kb[b]?delete a[b]:a[b]=Kb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Mb=c}return Mb}var Mb;function Nb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ob(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Pb=[31,29,31,30,31,30,31,31,30,31,30,31],Qb=[31,28,31,30,31,30,31,31,30,31,30,31];function Rb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Nb(a.getFullYear())?Pb:Qb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Sb(a,b,c,d){function e(h,q,u){for(h="number"===typeof h?h.toString():h||"";h.length<q;)h=u[0]+h;return h}function g(h,q){return e(h,q,"0")}function l(h,q){function u(Eb){return 0>Eb?-1:0<Eb?1:0}var B;0===(B=u(h.getFullYear()-q.getFullYear()))&&0===(B=u(h.getMonth()-q.getMonth()))&&(B=u(h.getDate()-q.getDate()));return B}function n(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function w(h){h=Rb(new Date(h.P+1900,0,1),h.fa);var q=new Date(h.getFullYear()+1,0,4),u=n(new Date(h.getFullYear(),0,4));q=n(q);return 0>=l(u,h)?0>=l(q,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var p=I[d+40>>2];d={Ka:I[d>>2],Ja:I[d+4>>2],da:I[d+8>>2],$:I[d+12>>2],Z:I[d+16>>2],P:I[d+20>>2],ea:I[d+24>>2],fa:I[d+28>>2],Ra:I[d+32>>2],Ia:I[d+36>>
2],La:p?wa(p):""};c=wa(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in p)c=c.replace(new RegExp(t,"g"),p[t]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
N="January February March April May June July August September October November December".split(" ");p={"%a":function(h){return y[h.ea].substring(0,3)},"%A":function(h){return y[h.ea]},"%b":function(h){return N[h.Z].substring(0,3)},"%B":function(h){return N[h.Z]},"%C":function(h){return g((h.P+1900)/100|0,2)},"%d":function(h){return g(h.$,2)},"%e":function(h){return e(h.$,2," ")},"%g":function(h){return w(h).toString().substring(2)},"%G":function(h){return w(h)},"%H":function(h){return g(h.da,2)},
"%I":function(h){h=h.da;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.$+Ob(Nb(h.P+1900)?Pb:Qb,h.Z-1),3)},"%m":function(h){return g(h.Z+1,2)},"%M":function(h){return g(h.Ja,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.da&&12>h.da?"AM":"PM"},"%S":function(h){return g(h.Ka,2)},"%t":function(){return"\t"},"%u":function(h){return h.ea||7},"%U":function(h){var q=new Date(h.P+1900,0,1),u=0===q.getDay()?q:Rb(q,7-q.getDay());h=new Date(h.P+1900,h.Z,h.$);return 0>l(u,h)?
g(Math.ceil((31-u.getDate()+(Ob(Nb(h.getFullYear())?Pb:Qb,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(u,q)?"01":"00"},"%V":function(h){var q=new Date(h.P+1901,0,4),u=n(new Date(h.P+1900,0,4));q=n(q);var B=Rb(new Date(h.P+1900,0,1),h.fa);return 0>l(B,u)?"53":0>=l(q,B)?"01":g(Math.ceil((u.getFullYear()<h.P+1900?h.fa+32-u.getDate():h.fa+1-u.getDate())/7),2)},"%w":function(h){return h.ea},"%W":function(h){var q=new Date(h.P,0,1),u=1===q.getDay()?q:Rb(q,0===q.getDay()?1:7-q.getDay()+1);h=new Date(h.P+
1900,h.Z,h.$);return 0>l(u,h)?g(Math.ceil((31-u.getDate()+(Ob(Nb(h.getFullYear())?Pb:Qb,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(u,q)?"01":"00"},"%y":function(h){return(h.P+1900).toString().substring(2)},"%Y":function(h){return h.P+1900},"%z":function(h){h=h.Ia;var q=0<=h;h=Math.abs(h)/60;return(q?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.La},"%%":function(){return"%"}};for(t in p)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),p[t](d)));t=$a(c,!1);if(t.length>
b)return 0;G.set(t,a);return t.length-1}function ob(a,b,c,d){a||(a=this);this.parent=a;this.T=a.T;this.ba=null;this.id=ib++;this.name=b;this.mode=c;this.M={};this.N={};this.rdev=d}Object.defineProperties(ob.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Fb();R=Array(4096);vb(P,"/");T("/tmp");T("/home");T("/home/web_user");
(function(){T("/dev");Ya(259,{read:function(){return 0},write:function(b,c,d,e){return e}});xb("/dev/null",259);Xa(1280,ab);Xa(1536,bb);xb("/dev/tty",1280);xb("/dev/tty1",1536);var a=Ua();V("random",a);V("urandom",a);T("/dev/shm");T("/dev/shm/tmp")})();
(function(){T("/proc");var a=T("/proc/self");T("/proc/self/fd");vb({T:function(){var b=db(a,"fd",16895,73);b.M={lookup:function(c,d){var e=Q[+d];if(!e)throw new O(8);c={parent:null,T:{ra:"fake"},M:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();function $a(a,b){var c=Array(ya(a)+1);a=ta(a,c,0,c.length);b&&(c.length=a);return c}
var Vb={a:function(a){return Tb(a+16)+16},b:function(a,b,c){(new Oa(a)).xa(b,c);Pa++;throw a;},f:function(a,b,c){X=c;try{var d=Z(a);switch(b){case 0:var e=Y();return 0>e?-28:U(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags|=e,0;case 12:return e=Y(),Aa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return I[Ub()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof W&&g instanceof O||C(g),-g.V}},q:function(a,b,c){X=c;
try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Y();return I[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Y();if(!d.N.ya)throw new O(59);return d.N.ya(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:C("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof W&&g instanceof O||C(g),-g.V}},h:function(a,b,c){X=c;try{var d=
wa(a),e=c?Y():0;return U(d,b,e).fd}catch(g){return"undefined"!==typeof W&&g instanceof O||C(g),-g.V}},e:function(){C("")},o:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Jb();else return I[Ub()>>2]=28,-1;I[b>>2]=a/1E3|0;I[b+4>>2]=a%1E3*1E6|0;return 0},j:function(a,b,c){F.copyWithin(a,b,b+c)},d:function(a){var b=F.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{oa.grow(Math.min(2147483648,
d)-za.byteLength+65535>>>16);Ba();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},m:function(a,b){var c=0;Lb().forEach(function(d,e){var g=b+c;e=I[a+4*e>>2]=g;for(g=0;g<d.length;++g)G[e++>>0]=d.charCodeAt(g);G[e>>0]=0;c+=d.length+1});return 0},n:function(a,b){var c=Lb();I[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});I[b>>2]=d;return 0},c:function(a){if(!(noExitRuntime||0<ma)){if(f.onExit)f.onExit(a);pa=!0}ea(a,new la(a))},g:function(a){try{var b=Z(a);Ab(b);return 0}catch(c){return"undefined"!==
typeof W&&c instanceof O||C(c),c.V}},p:function(a,b,c,d){try{a:{for(var e=Z(a),g=a=0;g<c;g++){var l=I[b+(8*g+4)>>2],n=e,w=I[b+8*g>>2],p=l,t=void 0,y=G;if(0>p||0>t)throw new O(28);if(null===n.fd)throw new O(8);if(1===(n.flags&2097155))throw new O(8);if(16384===(n.node.mode&61440))throw new O(31);if(!n.N.read)throw new O(28);var N="undefined"!==typeof t;if(!N)t=n.position;else if(!n.seekable)throw new O(70);var h=n.N.read(n,y,w,p,t);N||(n.position+=h);var q=h;if(0>q){var u=-1;break a}a+=q;if(q<l)break}u=
a}I[d>>2]=u;return 0}catch(B){return"undefined"!==typeof W&&B instanceof O||C(B),B.V}},k:function(a,b,c,d,e){try{var g=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Bb(g,a,d);Ma=[g.position>>>0,(M=g.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];I[e>>2]=Ma[0];I[e+4>>2]=Ma[1];g.ha&&0===a&&0===d&&(g.ha=null);return 0}catch(l){return"undefined"!==typeof W&&l instanceof O||C(l),l.V}},
i:function(a,b,c,d){try{a:{for(var e=Z(a),g=a=0;g<c;g++){var l=Cb(e,G,I[b+8*g>>2],I[b+(8*g+4)>>2]);if(0>l){var n=-1;break a}a+=l}n=a}I[d>>2]=n;return 0}catch(w){return"undefined"!==typeof W&&w instanceof O||C(w),w.V}},l:function(a,b,c,d){return Sb(a,b,c,d)}};
(function(){function a(e){f.asm=e.exports;oa=f.asm.r;Ba();Ca=f.asm.K;Ea.unshift(f.asm.s);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Ha&&(clearInterval(Ha),Ha=null),K&&(e=K,K=null,e()))}function b(e){a(e.instance)}function c(e){return La().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){D("failed to asynchronously prepare wasm: "+g);C(g)})}var d={a:Vb};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return D("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return E||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||L.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){D("wasm streaming compile failed: "+g);D("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.s).apply(null,arguments)};var Wb=f._Highs_create=function(){return(Wb=f._Highs_create=f.asm.t).apply(null,arguments)},Xb=f._Highs_destroy=function(){return(Xb=f._Highs_destroy=f.asm.u).apply(null,arguments)},Yb=f._Highs_run=function(){return(Yb=f._Highs_run=f.asm.v).apply(null,arguments)};f._Highs_readModel=function(){return(f._Highs_readModel=f.asm.w).apply(null,arguments)};
f._Highs_writeSolution=function(){return(f._Highs_writeSolution=f.asm.x).apply(null,arguments)};f._Highs_writeSolutionPretty=function(){return(f._Highs_writeSolutionPretty=f.asm.y).apply(null,arguments)};f._Highs_setBoolOptionValue=function(){return(f._Highs_setBoolOptionValue=f.asm.z).apply(null,arguments)};f._Highs_setIntOptionValue=function(){return(f._Highs_setIntOptionValue=f.asm.A).apply(null,arguments)};
f._Highs_setDoubleOptionValue=function(){return(f._Highs_setDoubleOptionValue=f.asm.B).apply(null,arguments)};f._Highs_setStringOptionValue=function(){return(f._Highs_setStringOptionValue=f.asm.C).apply(null,arguments)};var Zb=f._Highs_getModelStatus=function(){return(Zb=f._Highs_getModelStatus=f.asm.D).apply(null,arguments)};f._Highs_call=function(){return(f._Highs_call=f.asm.E).apply(null,arguments)};
var Ub=f.___errno_location=function(){return(Ub=f.___errno_location=f.asm.F).apply(null,arguments)},ua=f.stackSave=function(){return(ua=f.stackSave=f.asm.G).apply(null,arguments)},va=f.stackRestore=function(){return(va=f.stackRestore=f.asm.H).apply(null,arguments)},sa=f.stackAlloc=function(){return(sa=f.stackAlloc=f.asm.I).apply(null,arguments)},Tb=f._malloc=function(){return(Tb=f._malloc=f.asm.J).apply(null,arguments)};
f.cwrap=function(a,b,c,d){c=c||[];var e=c.every(function(g){return"number"===g});return"string"!==b&&e&&!d?qa(a):function(){return ra(a,b,c,arguments)}};var $b;function la(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function ac(){$b||bc();$b||(K=ac)};
function bc(){function a(){if(!$b&&($b=!0,f.calledRun=!0,!pa)){f.noFSInit||Gb||(Gb=!0,Fb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?V("stdin",f.stdin):yb("/dev/tty","/dev/stdin"),f.stdout?V("stdout",null,f.stdout):yb("/dev/tty","/dev/stdout"),f.stderr?V("stderr",null,f.stderr):yb("/dev/tty1","/dev/stderr"),U("/dev/stdin",0),U("/dev/stdout",1),U("/dev/stderr",1));jb=!1;Na(Ea);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&
(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Fa.unshift(b)}Na(Fa)}}if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ga();Na(Da);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=bc;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();bc();f.ta=f.cwrap("Highs_readModel","number",["number","string"]);
const cc=f.cwrap("Highs_setIntOptionValue","number",["number","string","number"]),dc=f.cwrap("Highs_setDoubleOptionValue","number",["number","string","number"]),ec=f.cwrap("Highs_setStringOptionValue","number",["number","string","string"]),fc=f.cwrap("Highs_setBoolOptionValue","number",["number","string","number"]);f.ua=f.cwrap("Highs_writeSolutionPretty","number",["number","string"]);
const gc={0:"Not Set",1:"Load error",2:"Model error",3:"Presolve error",4:"Solve error",5:"Postsolve error",6:"Empty",7:"Optimal",8:"Infeasible",9:"Primal infeasible or unbounded",10:"Unbounded",11:"Bound on objective reached",12:"Target for objective reached",13:"Time limit reached",14:"Iteration limit reached",15:"Unknown"};
f.solve=function(a,b){Db(a);const c=Wb();hc(()=>f.ta(c,"m.lp"),"read LP model (see http://web.mit.edu/lpsolve/doc/CPLEX-format.htm)");a=b||{};for(const d in a){const e=a[d];b=typeof e;let g;if("number"===b)g=ic;else if("boolean"===b)g=fc;else if("string"===b)g=ec;else throw Error(`Unsupported option value type ${e} for '${d}'`);hc(()=>g(c,d,e),`set option '${d}'`)}hc(()=>Yb(c),"solve the problem");a=gc[Zb(c,0)]||"Unrecognised HiGHS model status";k.length=0;hc(()=>f.ua(c,""),"write and extract solution");
Xb(c);a=jc(a);k.length=0;ca.length=0;return a};function ic(a,b,c){let d=dc(a,b,c);-1===d&&c===(c|0)&&(d=cc(a,b,c));return d}function kc(a){return"inf"===a?1/0:"-inf"===a?-1/0:+a}const lc={Index:a=>parseInt(a),Lower:kc,Upper:kc,Primal:kc,Dual:kc};function mc(a,b){const c=b.match(/[^\s]+/g)||[],d={};for(let g=0;g<c.length;g++){if(g>=a.length)throw Error("Unable to parse solution line: "+b);var e=c[g];const l=a[g],n=lc[l];e=n?n(e):e;d[l]=e}return d}
function jc(a){if(3>k.length)throw Error("Unable to parse solution. Too few lines.");let b=k[1].match(/[^\s]+/g)||[];const c=-1===b.indexOf("Type"),d="Infeasible"===a;var e=l=>!(d&&("Status"===l||"Dual"===l||"Primal"===l)||!c&&("Status"===l||"Dual"===l));b=b.filter(e);a={Status:a,Columns:{},Rows:[],IsLinear:c};for(var g=2;"Rows"!=k[g];g++){const l=mc(b,k[g]);a.Columns[l.Name]=l}b=(k[g+1].match(/[^\s]+/g)||[]).filter(e);for(e=g+2;e<k.length;e++)a.Rows.push(mc(b,k[e]));return a}
function hc(a,b){let c;try{c=a()}catch(d){c=d}if(0!==c)throw Error("Unable to "+b+". HiGHS error "+c);};


  return Module.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Module; });
else if (typeof exports === 'object')
  exports["Module"] = Module;
