
var Module = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(moduleArg = {}) {

var h=moduleArg,aa,ba;h.ready=new Promise((a,b)=>{aa=a;ba=b});const k=[],ca=[];h.print=a=>k.push(a);h.printErr=a=>ca.push(a);var da=Object.assign({},h),ea="./this.program",fa=(a,b)=>{throw b;},ha="object"==typeof window,n="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,u="",ja,ka,la;
if(ia){var fs=require("fs"),ma=require("path");u=n?ma.dirname(u)+"/":__dirname+"/";ja=(a,b)=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};la=a=>{a=ja(a,!0);a.buffer||(a=new Uint8Array(a));return a};ka=(a,b,c,d=!0)=>{a=na(a)?new URL(a):ma.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,g)=>{e?c(e):b(d?g.buffer:g)})};!h.thisProgram&&1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;};h.inspect=()=>
"[Emscripten Module object]"}else if(ha||n)n?u=self.location.href:"undefined"!=typeof document&&document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),u=0!==u.indexOf("blob:")?u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=h.print||console.log.bind(console),v=h.printErr||console.error.bind(console);Object.assign(h,da);da=null;h.thisProgram&&(ea=h.thisProgram);h.quit&&(fa=h.quit);var y;h.wasmBinary&&(y=h.wasmBinary);"object"!=typeof WebAssembly&&A("no native wasm support detected");var pa,qa=!1,B,C,ra,E,F;
function sa(){var a=pa.buffer;h.HEAP8=B=new Int8Array(a);h.HEAP16=ra=new Int16Array(a);h.HEAPU8=C=new Uint8Array(a);h.HEAPU16=new Uint16Array(a);h.HEAP32=E=new Int32Array(a);h.HEAPU32=F=new Uint32Array(a);h.HEAPF32=new Float32Array(a);h.HEAPF64=new Float64Array(a)}var ta=[],ua=[],va=[];function wa(){var a=h.preRun.shift();ta.unshift(a)}var G=0,xa=null,H=null;
function A(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";v(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var ya=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),I;I="highs.wasm";if(!ya(I)){var za=I;I=h.locateFile?h.locateFile(za,u):u+za}function Aa(a){if(a==I&&y)return new Uint8Array(y);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}
function Ba(a){if(!y&&(ha||n)){if("function"==typeof fetch&&!na(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Aa(a));if(ka)return new Promise((b,c)=>{ka(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Aa(a))}function Ca(a,b,c){return Ba(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v(`failed to asynchronously prepare wasm: ${d}`);A(d)})}
function Da(a,b){var c=I;return y||"function"!=typeof WebAssembly.instantiateStreaming||ya(c)||na(c)||ia||"function"!=typeof fetch?Ca(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v(`wasm streaming compile failed: ${e}`);v("falling back to ArrayBuffer instantiation");return Ca(c,a,b)}))}var J,Ea;function Fa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ga=a=>{for(;0<a.length;)a.shift()(h)},Ha=h.noExitRuntime||!0;function Ia(a){this.aa=a-24;this.Fa=function(b){F[this.aa+4>>2]=b};this.Ea=function(b){F[this.aa+8>>2]=b};this.va=function(b,c){this.Da();this.Fa(b);this.Ea(c)};this.Da=function(){F[this.aa+16>>2]=0}}
var Ja=0,Ka=0,La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},K=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ma=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+
b},Oa=a=>{if("/"===a)return"/";a=K(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Pa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ia)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}A("initRandomDevice")},Qa=a=>(Qa=Pa())(a);
function Ra(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=La(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Sa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L=(a,b)=>{for(var c=b+void 0,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Sa)return Sa.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
Ta=[],Ua=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Va=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var r=a.charCodeAt(++g);l=65536+((l&1023)<<10)|r&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&
63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e};function Wa(a,b){var c=Array(Ua(a)+1);a=Va(a,c,0,c.length);b&&(c.length=a);return c}var Xa=[];function Ya(a,b){Xa[a]={input:[],output:[],T:b};Za(a,$a)}
var $a={open(a){var b=Xa[a.node.rdev];if(!b)throw new M(43);a.tty=b;a.seekable=!1},close(a){a.tty.T.fsync(a.tty)},fsync(a){a.tty.T.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.T.na)throw new M(60);for(var e=0,g=0;g<d;g++){try{var l=a.tty.T.na(a.tty)}catch(r){throw new M(29);}if(void 0===l&&0===e)throw new M(6);if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.T.ga)throw new M(60);try{for(var e=0;e<d;e++)a.tty.T.ga(a.tty,b[c+e])}catch(g){throw new M(29);
}d&&(a.node.timestamp=Date.now());return e}},ab={na(){a:{if(!Ta.length){var a=null;if(ia){a=Buffer.alloc(256);var b=0,c=process.stdin.fd;try{b=fs.readSync(c,a)}catch(d){if(d.toString().includes("EOF"))b=0;else throw d;}a=0<b?a.slice(0,b).toString("utf-8"):null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Ta=Wa(a,!0)}a=Ta.shift()}return a},ga(a,
b){null===b||10===b?(oa(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(L(a.output,0)),a.output=[])},xa(){return{Oa:25856,Qa:5,Na:191,Pa:35387,Ma:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ya(){return 0},za(){return[24,80]}},bb={ga(a,b){null===b||10===b?(v(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(v(L(a.output,0)),a.output=[])}};
function cb(a,b){var c=a.K?a.K.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.K,a.K=new Uint8Array(b),0<a.N&&a.K.set(c.subarray(0,a.N),0))}
var O={O:null,S(){return O.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);O.O||(O.O={dir:{node:{U:O.L.U,P:O.L.P,lookup:O.L.lookup,Z:O.L.Z,rename:O.L.rename,unlink:O.L.unlink,rmdir:O.L.rmdir,readdir:O.L.readdir,symlink:O.L.symlink},stream:{W:O.M.W}},file:{node:{U:O.L.U,P:O.L.P},stream:{W:O.M.W,read:O.M.read,write:O.M.write,ja:O.M.ja,oa:O.M.oa,qa:O.M.qa}},link:{node:{U:O.L.U,P:O.L.P,readlink:O.L.readlink},stream:{}},ka:{node:{U:O.L.U,P:O.L.P},
stream:db}});c=eb(a,b,c,d);16384===(c.mode&61440)?(c.L=O.O.dir.node,c.M=O.O.dir.stream,c.K={}):32768===(c.mode&61440)?(c.L=O.O.file.node,c.M=O.O.file.stream,c.N=0,c.K=null):40960===(c.mode&61440)?(c.L=O.O.link.node,c.M=O.O.link.stream):8192===(c.mode&61440)&&(c.L=O.O.ka.node,c.M=O.O.ka.stream);c.timestamp=Date.now();a&&(a.K[b]=c,a.timestamp=c.timestamp);return c},Ra(a){return a.K?a.K.subarray?a.K.subarray(0,a.N):new Uint8Array(a.K):new Uint8Array(0)},L:{U(a){var b={};b.dev=8192===(a.mode&61440)?a.id:
1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.N:40960===(a.mode&61440)?a.link.length:0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ta=4096;b.blocks=Math.ceil(b.size/b.ta);return b},P(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.N!=b))if(0==b)a.K=null,a.N=0;else{var c=a.K;a.K=new Uint8Array(b);c&&a.K.set(c.subarray(0,
Math.min(b,a.N)));a.N=b}},lookup(){throw fb[44];},Z(a,b,c,d){return O.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=gb(b,c)}catch(g){}if(d)for(var e in d.K)throw new M(55);}delete a.parent.K[a.name];a.parent.timestamp=Date.now();a.name=c;b.K[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.K[b];a.timestamp=Date.now()},rmdir(a,b){var c=gb(a,b),d;for(d in c.K)throw new M(55);delete a.K[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.K)a.K.hasOwnProperty(c)&&
b.push(c);return b},symlink(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},M:{read(a,b,c,d,e){var g=a.node.K;if(e>=a.node.N)return 0;a=Math.min(a.node.N-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===B.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.K||a.K.subarray)){if(g)return a.K=b.subarray(c,c+d),a.N=d;if(0===
a.N&&0===e)return a.K=b.slice(c,c+d),a.N=d;if(e+d<=a.N)return a.K.set(b.subarray(c,c+d),e),d}cb(a,e+d);if(a.K.subarray&&b.subarray)a.K.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.K[e+g]=b[c+g];a.N=Math.max(a.N,e+d);return d},W(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.N);if(0>b)throw new M(28);return b},ja(a,b,c){cb(a.node,b+c);a.node.N=Math.max(a.node.N,b+c)},oa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.K;if(e&2||a.buffer!==B.buffer){if(0<
c||c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;A();b=void 0;if(!b)throw new M(48);B.set(a,b)}else c=!1,b=a.byteOffset;return{aa:b,La:c}},qa(a,b,c,d){O.M.write(a,b,0,d,c,!1);return 0}}},hb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ib=null,jb={},P=[],kb=1,Q=null,lb=!0,M=null,fb={};
function R(a,b={}){a=Ra(a);if(!a)return{path:"",node:null};b=Object.assign({ma:!0,ha:0},b);if(8<b.ha)throw new M(32);a=a.split("/").filter(l=>!!l);for(var c=ib,d="/",e=0;e<a.length;e++){var g=e===a.length-1;if(g&&b.parent)break;c=gb(c,a[e]);d=K(d+"/"+a[e]);c.$&&(!g||g&&b.ma)&&(c=c.$.root);if(!g||b.la)for(g=0;40960===(c.mode&61440);)if(c=mb(d),d=Ra(Ma(d),c),c=R(d,{ha:b.ha+1}).node,40<g++)throw new M(32);}return{path:d,node:c}}
function nb(a){for(var b;;){if(a===a.parent)return a=a.S.pa,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function gb(a,b){var c;if(c=(c=pb(a,"x"))?c:a.L.lookup?0:2)throw new M(c,a);for(c=Q[ob(a.id,b)];c;c=c.Ba){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.L.lookup(a,b)}
function eb(a,b,c,d){a=new qb(a,b,c,d);b=ob(a.parent.id,a.name);a.Ba=Q[b];return Q[b]=a}function rb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function pb(a,b){if(lb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function sb(a,b){try{return gb(a,b),20}catch(c){}return pb(a,"wx")}function tb(){for(var a=0;4096>=a;a++)if(!P[a])return a;throw new M(33);}
function S(a){a=P[a];if(!a)throw new M(8);return a}function ub(a,b=-1){T||(T=function(){this.ba={}},T.prototype={},Object.defineProperties(T.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ba.flags},set(c){this.ba.flags=c}},position:{get(){return this.ba.position},set(c){this.ba.position=c}}}));a=Object.assign(new T,a);-1==b&&(b=tb());a.fd=b;return P[b]=a}var db={open(a){a.M=jb[a.node.rdev].M;a.M.open&&a.M.open(a)},W(){throw new M(70);}};
function Za(a,b){jb[a]={M:b}}function vb(a,b){var c="/"===b,d=!b;if(c&&ib)throw new M(10);if(!c&&!d){var e=R(b,{ma:!1});b=e.path;e=e.node;if(e.$)throw new M(10);if(16384!==(e.mode&61440))throw new M(54);}b={type:a,Sa:{},pa:b,Aa:[]};a=a.S(b);a.S=b;b.root=a;c?ib=a:e&&(e.$=b,e.S&&e.S.Aa.push(b))}function wb(a,b,c){var d=R(a,{parent:!0}).node;a=Oa(a);if(!a||"."===a||".."===a)throw new M(28);var e=sb(d,a);if(e)throw new M(e);if(!d.L.Z)throw new M(63);return d.L.Z(d,a,b,c)}
function U(a){return wb(a,16895,0)}function xb(a,b,c){"undefined"==typeof c&&(c=b,b=438);wb(a,b|8192,c)}function yb(a,b){if(!Ra(a))throw new M(44);var c=R(b,{parent:!0}).node;if(!c)throw new M(44);b=Oa(b);var d=sb(c,b);if(d)throw new M(d);if(!c.L.symlink)throw new M(63);c.L.symlink(c,b,a)}function mb(a){a=R(a).node;if(!a)throw new M(44);if(!a.L.readlink)throw new M(28);return Ra(nb(a.parent),a.L.readlink(a))}
function V(a,b,c){if(""===a)throw new M(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=K(a);try{e=R(a,{la:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new M(20);}else e=wb(a,c,0),d=!0;if(!e)throw new M(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new M(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==rb(b)||b&512)?31:pb(e,rb(b)):44))throw new M(c);if(b&512&&!d){c=e;c="string"==typeof c?R(c,{la:!0}).node:c;if(!c.L.P)throw new M(63);if(16384===(c.mode&61440))throw new M(31);if(32768!==(c.mode&61440))throw new M(28);if(d=pb(c,"w"))throw new M(d);c.L.P(c,{size:0,timestamp:Date.now()})}b&=-131713;e=ub({node:e,path:nb(e),flags:b,seekable:!0,position:0,M:e.M,Ka:[],error:!1});e.M.open&&e.M.open(e);!h.logReadFiles||b&1||(zb||(zb={}),
a in zb||(zb[a]=1));return e}function Ab(a){if(null===a.fd)throw new M(8);a.fa&&(a.fa=null);try{a.M.close&&a.M.close(a)}catch(b){throw b;}finally{P[a.fd]=null}a.fd=null}function Bb(a,b,c){if(null===a.fd)throw new M(8);if(!a.seekable||!a.M.W)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.M.W(a,b,c);a.Ka=[]}
function Cb(a,b,c,d,e,g){if(0>d||0>e)throw new M(28);if(null===a.fd)throw new M(8);if(0===(a.flags&2097155))throw new M(8);if(16384===(a.node.mode&61440))throw new M(31);if(!a.M.write)throw new M(28);a.seekable&&a.flags&1024&&Bb(a,0,2);var l="undefined"!=typeof e;if(!l)e=a.position;else if(!a.seekable)throw new M(70);b=a.M.write(a,b,c,d,e,g);l||(a.position+=b);return b}
function Db(a){var b={};b.flags=b.flags||577;var c=V("m.lp",b.flags,b.mode);if("string"==typeof a){var d=new Uint8Array(Ua(a)+1);a=Va(a,d,0,d.length);Cb(c,d,0,a,void 0,b.ua)}else if(ArrayBuffer.isView(a))Cb(c,a,0,a.byteLength,void 0,b.ua);else throw Error("Unsupported data type");Ab(c)}
function Eb(){M||(M=function(a,b){this.name="ErrnoError";this.node=b;this.Ca=function(c){this.V=c};this.Ca(a);this.message="FS error"},M.prototype=Error(),M.prototype.constructor=M,[44].forEach(a=>{fb[a]=new M(a);fb[a].stack="<generic error, no stack>"}))}var Fb;
function W(a,b,c){a=K("/dev/"+a);var d=hb(!!b,!!c);Gb||(Gb=64);var e=Gb++<<8|0;Za(e,{open(g){g.seekable=!1},close(){c&&c.buffer&&c.buffer.length&&c(10)},read(g,l,r,x){for(var m=0,q=0;q<x;q++){try{var w=b()}catch(D){throw new M(29);}if(void 0===w&&0===m)throw new M(6);if(null===w||void 0===w)break;m++;l[r+q]=w}m&&(g.node.timestamp=Date.now());return m},write(g,l,r,x){for(var m=0;m<x;m++)try{c(l[r+m])}catch(q){throw new M(29);}x&&(g.node.timestamp=Date.now());return m}});xb(a,d,e)}
var Gb,X={},T,zb,Hb=void 0;function Y(){var a=E[+Hb>>2];Hb+=4;return a}
var Ib={},Kb=()=>{if(!Jb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ib)void 0===Ib[b]?delete a[b]:a[b]=Ib[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Jb=c}return Jb},Jb,Lb=a=>0===a%4&&(0!==a%100||0===a%400),Mb=[31,29,31,30,31,30,31,31,30,31,30,31],Nb=[31,28,31,30,31,30,31,31,30,31,30,31],Ob=(a,b,c,d)=>{function e(f,
p,t){for(f="number"==typeof f?f.toString():f||"";f.length<p;)f=t[0]+f;return f}function g(f,p){return e(f,p,"0")}function l(f,p){function t(N){return 0>N?-1:0<N?1:0}var z;0===(z=t(f.getFullYear()-p.getFullYear()))&&0===(z=t(f.getMonth()-p.getMonth()))&&(z=t(f.getDate()-p.getDate()));return z}function r(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),0,2);case 4:return new Date(f.getFullYear(),
0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function x(f){var p=f.X;for(f=new Date((new Date(f.Y+1900,0,1)).getTime());0<p;){var t=f.getMonth(),z=(Lb(f.getFullYear())?Mb:Nb)[t];if(p>z-f.getDate())p-=z-f.getDate()+1,f.setDate(1),11>t?f.setMonth(t+1):(f.setMonth(0),f.setFullYear(f.getFullYear()+1));else{f.setDate(f.getDate()+p);break}}t=new Date(f.getFullYear()+1,0,4);p=r(new Date(f.getFullYear(),0,4));t=r(t);return 0>=l(p,f)?0>=l(t,f)?f.getFullYear()+
1:f.getFullYear():f.getFullYear()-1}var m=F[d+40>>2];d={Ia:E[d>>2],Ha:E[d+4>>2],da:E[d+8>>2],ia:E[d+12>>2],ea:E[d+16>>2],Y:E[d+20>>2],R:E[d+24>>2],X:E[d+28>>2],Ta:E[d+32>>2],Ga:E[d+36>>2],Ja:m?m?L(C,m):"":""};c=c?L(C,c):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m",
"%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),D="January February March April May June July August September October November December".split(" ");m={"%a":f=>w[f.R].substring(0,3),"%A":f=>w[f.R],"%b":f=>D[f.ea].substring(0,3),"%B":f=>D[f.ea],"%C":f=>g((f.Y+1900)/100|0,2),"%d":f=>g(f.ia,2),"%e":f=>e(f.ia,2," "),"%g":f=>x(f).toString().substring(2),
"%G":f=>x(f),"%H":f=>g(f.da,2),"%I":f=>{f=f.da;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":f=>{for(var p=0,t=0;t<=f.ea-1;p+=(Lb(f.Y+1900)?Mb:Nb)[t++]);return g(f.ia+p,3)},"%m":f=>g(f.ea+1,2),"%M":f=>g(f.Ha,2),"%n":()=>"\n","%p":f=>0<=f.da&&12>f.da?"AM":"PM","%S":f=>g(f.Ia,2),"%t":()=>"\t","%u":f=>f.R||7,"%U":f=>g(Math.floor((f.X+7-f.R)/7),2),"%V":f=>{var p=Math.floor((f.X+7-(f.R+6)%7)/7);2>=(f.R+371-f.X-2)%7&&p++;if(p)53==p&&(t=(f.R+371-f.X)%7,4==t||3==t&&Lb(f.Y)||(p=1));else{p=52;var t=(f.R+7-f.X-
1)%7;(4==t||5==t&&Lb(f.Y%400-1))&&p++}return g(p,2)},"%w":f=>f.R,"%W":f=>g(Math.floor((f.X+7-(f.R+6)%7)/7),2),"%y":f=>(f.Y+1900).toString().substring(2),"%Y":f=>f.Y+1900,"%z":f=>{f=f.Ga;var p=0<=f;f=Math.abs(f)/60;return(p?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":f=>f.Ja,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(q in m)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),m[q](d)));c=c.replace(/\0\0/g,"%");q=Wa(c,!1);if(q.length>b)return 0;B.set(q,a);return q.length-1},Sb=(a,b,c,d)=>
{var e={string:m=>{var q=0;if(null!==m&&void 0!==m&&0!==m){q=Ua(m)+1;var w=Pb(q);Va(m,C,w,q);q=w}return q},array:m=>{var q=Pb(m.length);B.set(m,q);return q}};a=h["_"+a];var g=[],l=0;if(d)for(var r=0;r<d.length;r++){var x=e[c[r]];x?(0===l&&(l=Qb()),g[r]=x(d[r])):g[r]=d[r]}c=a.apply(null,g);return c=function(m){0!==l&&Rb(l);return"string"===b?m?L(C,m):"":"boolean"===b?!!m:m}(c)};
function qb(a,b,c,d){a||(a=this);this.parent=a;this.S=a.S;this.$=null;this.id=kb++;this.name=b;this.mode=c;this.L={};this.M={};this.rdev=d}Object.defineProperties(qb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Eb();Q=Array(4096);vb(O,"/");U("/tmp");U("/home");U("/home/web_user");
(function(){U("/dev");Za(259,{read:()=>0,write:(d,e,g,l)=>l});xb("/dev/null",259);Ya(1280,ab);Ya(1536,bb);xb("/dev/tty",1280);xb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Qa(a).byteLength);return a[--b]};W("random",c);W("urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");vb({S(){var b=eb(a,"fd",16895,73);b.L={lookup(c,d){var e=S(+d);c={parent:null,S:{pa:"fake"},L:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
var Ub={a:(a,b,c)=>{(new Ia(a)).va(b,c);Ja=a;Ka++;throw Ja;},d:function(a,b,c){Hb=c;try{var d=S(a);switch(b){case 0:var e=Y();if(0>e)return-28;for(;P[e];)e++;return ub(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Y(),d.flags|=e,0;case 5:return e=Y(),ra[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return E[Tb()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof X||"ErrnoError"!==g.name)throw g;return-g.V}},q:function(a,b,c){Hb=c;try{var d=S(a);
switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.T.xa){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Y();E[e>>2]=25856;E[e+4>>2]=5;E[e+8>>2]=191;E[e+12>>2]=35387;for(var g=0;32>g;g++)B[e+g+17>>0]=b[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.T.ya)for(e=Y(),b=[],g=0;32>g;g++)b.push(B[e+g+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=Y();return E[e>>
2]=0;case 21520:return d.tty?-28:-59;case 21531:e=Y();if(!d.M.wa)throw new M(59);return d.M.wa(d,b,e);case 21523:if(!d.tty)return-59;d.tty.T.za&&(g=[24,80],e=Y(),ra[e>>1]=g[0],ra[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(l){if("undefined"==typeof X||"ErrnoError"!==l.name)throw l;return-l.V}},f:function(a,b,c,d){Hb=d;try{b=b?L(C,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?"/":S(a).path;if(0==e.length)throw new M(44);b=
K(g+"/"+e)}var l=d?Y():0;return V(b,c,l).fd}catch(r){if("undefined"==typeof X||"ErrnoError"!==r.name)throw r;return-r.V}},n:()=>!0,c:()=>{A("")},o:()=>Date.now(),b:()=>performance.now(),i:(a,b,c)=>C.copyWithin(a,b,b+c),r:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-pa.buffer.byteLength+65535)/65536;try{pa.grow(e);sa();var g=1;break a}catch(l){}g=
void 0}if(g)return!0}return!1},l:(a,b)=>{var c=0;Kb().forEach((d,e)=>{var g=b+c;e=F[a+4*e>>2]=g;for(g=0;g<d.length;++g)B[e++>>0]=d.charCodeAt(g);B[e>>0]=0;c+=d.length+1});return 0},m:(a,b)=>{var c=Kb();F[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);F[b>>2]=d;return 0},h:a=>{if(!Ha){if(h.onExit)h.onExit(a);qa=!0}fa(a,new Fa(a))},e:function(a){try{var b=S(a);Ab(b);return 0}catch(c){if("undefined"==typeof X||"ErrnoError"!==c.name)throw c;return c.V}},p:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var g,
l=b=0;l<c;l++){var r=F[a>>2],x=F[a+4>>2];a+=8;var m=e,q=r,w=x,D=g,f=B;if(0>w||0>D)throw new M(28);if(null===m.fd)throw new M(8);if(1===(m.flags&2097155))throw new M(8);if(16384===(m.node.mode&61440))throw new M(31);if(!m.M.read)throw new M(28);var p="undefined"!=typeof D;if(!p)D=m.position;else if(!m.seekable)throw new M(70);var t=m.M.read(m,f,q,w,D);p||(m.position+=t);var z=t;if(0>z){var N=-1;break a}b+=z;if(z<x)break;"undefined"!==typeof g&&(g+=z)}N=b}F[d>>2]=N;return 0}catch(Na){if("undefined"==
typeof X||"ErrnoError"!==Na.name)throw Na;return Na.V}},j:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var g=S(a);Bb(g,b,d);Ea=[g.position>>>0,(J=g.position,1<=+Math.abs(J)?0<J?+Math.floor(J/4294967296)>>>0:~~+Math.ceil((J-+(~~J>>>0))/4294967296)>>>0:0)];E[e>>2]=Ea[0];E[e+4>>2]=Ea[1];g.fa&&0===b&&0===d&&(g.fa=null);return 0}catch(l){if("undefined"==typeof X||"ErrnoError"!==l.name)throw l;return l.V}},g:function(a,b,c,d){try{a:{var e=S(a);a=b;for(var g,
l=b=0;l<c;l++){var r=F[a>>2],x=F[a+4>>2];a+=8;var m=Cb(e,B,r,x,g);if(0>m){var q=-1;break a}b+=m;"undefined"!==typeof g&&(g+=m)}q=b}F[d>>2]=q;return 0}catch(w){if("undefined"==typeof X||"ErrnoError"!==w.name)throw w;return w.V}},k:(a,b,c,d)=>Ob(a,b,c,d)},Z=function(){function a(c){Z=c.exports;pa=Z.s;sa();ua.unshift(Z.t);G--;h.monitorRunDependencies&&h.monitorRunDependencies(G);0==G&&(null!==xa&&(clearInterval(xa),xa=null),H&&(c=H,H=null,c()));return Z}var b={a:Ub};G++;h.monitorRunDependencies&&h.monitorRunDependencies(G);
if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){v(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Da(b,function(c){a(c.instance)}).catch(ba);return{}}(),Vb=h._Highs_create=()=>(Vb=h._Highs_create=Z.u)(),Wb=h._Highs_destroy=a=>(Wb=h._Highs_destroy=Z.v)(a),Xb=h._Highs_run=a=>(Xb=h._Highs_run=Z.w)(a);h._Highs_readModel=(a,b)=>(h._Highs_readModel=Z.x)(a,b);h._Highs_writeSolution=(a,b)=>(h._Highs_writeSolution=Z.y)(a,b);
h._Highs_writeSolutionPretty=(a,b)=>(h._Highs_writeSolutionPretty=Z.z)(a,b);h._Highs_setBoolOptionValue=(a,b,c)=>(h._Highs_setBoolOptionValue=Z.A)(a,b,c);h._Highs_setIntOptionValue=(a,b,c)=>(h._Highs_setIntOptionValue=Z.B)(a,b,c);h._Highs_setDoubleOptionValue=(a,b,c)=>(h._Highs_setDoubleOptionValue=Z.C)(a,b,c);h._Highs_setStringOptionValue=(a,b,c)=>(h._Highs_setStringOptionValue=Z.D)(a,b,c);var Yb=h._Highs_getModelStatus=a=>(Yb=h._Highs_getModelStatus=Z.E)(a);
h._Highs_call=(a,b,c,d,e,g,l,r,x,m,q,w,D,f,p,t,z,N)=>(h._Highs_call=Z.F)(a,b,c,d,e,g,l,r,x,m,q,w,D,f,p,t,z,N);var Tb=()=>(Tb=Z.G)(),Qb=()=>(Qb=Z.H)(),Rb=a=>(Rb=Z.I)(a),Pb=a=>(Pb=Z.J)(a);h.cwrap=(a,b,c,d)=>{var e=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&e&&!d?h["_"+a]:function(){return Sb(a,b,c,arguments)}};var Zb;H=function $b(){Zb||ac();Zb||(H=$b)};
function ac(){function a(){if(!Zb&&(Zb=!0,h.calledRun=!0,!qa)){h.noFSInit||Fb||(Fb=!0,Eb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?W("stdin",h.stdin):yb("/dev/tty","/dev/stdin"),h.stdout?W("stdout",null,h.stdout):yb("/dev/tty","/dev/stdout"),h.stderr?W("stderr",null,h.stderr):yb("/dev/tty1","/dev/stderr"),V("/dev/stdin",0),V("/dev/stdout",1),V("/dev/stderr",1));lb=!1;Ga(ua);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==typeof h.postRun&&
(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();va.unshift(b)}Ga(va)}}if(!(0<G)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)wa();Ga(ta);0<G||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();ac();h.ra=h.cwrap("Highs_readModel","number",["number","string"]);
const bc=h.cwrap("Highs_setIntOptionValue","number",["number","string","number"]),cc=h.cwrap("Highs_setDoubleOptionValue","number",["number","string","number"]),dc=h.cwrap("Highs_setStringOptionValue","number",["number","string","string"]),ec=h.cwrap("Highs_setBoolOptionValue","number",["number","string","number"]);h.sa=h.cwrap("Highs_writeSolutionPretty","number",["number","string"]);
const fc={0:"Not Set",1:"Load error",2:"Model error",3:"Presolve error",4:"Solve error",5:"Postsolve error",6:"Empty",7:"Optimal",8:"Infeasible",9:"Primal infeasible or unbounded",10:"Unbounded",11:"Bound on objective reached",12:"Target for objective reached",13:"Time limit reached",14:"Iteration limit reached",15:"Unknown"};
h.solve=function(a,b){Db(a);const c=Vb();gc(()=>h.ra(c,"m.lp"),"read LP model (see http://web.mit.edu/lpsolve/doc/CPLEX-format.htm)");a=b||{};for(const d in a){const e=a[d];b=typeof e;let g;if("number"===b)g=hc;else if("boolean"===b)g=ec;else if("string"===b)g=dc;else throw Error(`Unsupported option value type ${e} for '${d}'`);gc(()=>g(c,d,e),`set option '${d}'`)}gc(()=>Xb(c),"solve the problem");a=fc[Yb(c,0)]||"Unknown";k.length=0;gc(()=>h.sa(c,""),"write and extract solution");Wb(c);a=ic(a);k.length=
0;ca.length=0;return a};function hc(a,b,c){let d=cc(a,b,c);-1===d&&c===(c|0)&&(d=bc(a,b,c));return d}function jc(a){return"inf"===a?1/0:"-inf"===a?-1/0:+a}const kc={Index:a=>parseInt(a),Lower:jc,Upper:jc,Primal:jc,Dual:jc};function lc(a,b){const c=b.match(/[^\s]+/g)||[],d={};for(let g=0;g<c.length;g++){if(g>=a.length)throw Error("Unable to parse solution line: "+b);var e=c[g];const l=a[g],r=kc[l];e=r?r(e):e;d[l]=e}return d}
function ic(a){if(3>k.length)throw Error("Unable to parse solution. Too few lines.");let b=mc(k[1],k[2]);a={Status:a,Columns:{},Rows:[],ObjectiveValue:NaN};for(var c=2;"Rows"!=k[c];c++){const d=lc(b,k[c]);a.Columns[d.Name]=d}b=mc(k[c+1],k[c+2]);for(c+=2;""!=k[c];c++)a.Rows.push(lc(b,k[c]));a.ObjectiveValue=jc(k[c+3].match(/Objective value: (.+)/)[1]);return a}function mc(a,b){return[...a.matchAll(/[^\s]+/g)].filter(c=>" "!==b[c.index]||" "!==b[c.index+c[0].length-1]).map(c=>c[0])}
function gc(a,b){let c;try{c=a()}catch(d){c=d}if(0!==c&&1!==c)throw Error("Unable to "+b+". HiGHS error "+c);};


  return moduleArg.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Module;
else if (typeof define === 'function' && define['amd'])
  define([], () => Module);
